#!/usr/bin/env bash
#================================================================
# MOA Collaborative Writer
# Enables multiple agents to write together on shared documents
#================================================================

set -e

OUTPUT_DIR="${1:-.}"
mkdir -p "${OUTPUT_DIR}"

# Section markers
SECTION_START="<!-- SECTION:"
SECTION_END="<!-- /SECTION -->"

# Initialize a collaborative document
init_doc() {
    local doc_name="$1"
    local doc_file="${OUTPUT_DIR}/${doc_name}.md"

    cat > "$doc_file" <<'EOF'
# Collaborative Document

*Generated by MOA Multi-Agent System*
*Last updated: TIMESTAMP*

## Sections

<!-- AGENT_COORDINATION
{
  "sections": [],
  "writers": {},
  "status": "initialized"
}
-->

EOF

    sed -i "s/TIMESTAMP/$(date '+%Y-%m-%d %H:%M:%S')/" "$doc_file"
    echo "Initialized: ${doc_file}"
}

# Register a section for an agent
register_section() {
    local doc_name="$1"
    local section_id="$2"
    local agent_name="$3"
    local doc_file="${OUTPUT_DIR}/${doc_name}.md"

    if [[ ! -f "$doc_file" ]]; then
        init_doc "$doc_name"
    fi

    # Add section marker
    cat >> "$doc_file" <<EOF

${SECTION_START} ${section_id} -->
<!-- Writer: ${agent_name} -->
<!-- Status: pending -->
<!-- /SECTION -->

EOF

    echo "Registered section ${section_id} for ${agent_name}"
}

# Agent writes to their section
write_section() {
    local doc_name="$1"
    local section_id="$2"
    local agent_name="$3"
    local content="$4"
    local doc_file="${OUTPUT_DIR}/${doc_name}.md"

    # Create temp file with section
    local temp_file=$(mktemp)

    # Extract sections before target
    awk "/${SECTION_START} ${section_id} -->/,/${SECTION_END}/ {next} {print}" "$doc_file" > "$temp_file"

    # Add new section
    cat >> "$temp_file" <<EOF

${SECTION_START} ${section_id} -->
<!-- Writer: ${agent_name} -->
<!-- Status: completed -->
<!-- Last update: $(date '+%Y-%m-%d %H:%M:%S') -->

${content}
${SECTION_END}

EOF

    # Also append remaining sections
    local found=0
    while IFS= read -r line; do
        if [[ "$line" == *"${SECTION_START} ${section_id}"* ]]; then
            found=1
            # Skip until end marker
            while IFS= read -r l; do
                [[ "$l" == *"${SECTION_END}"* ]] && break
            done
        else
            echo "$line" >> "$temp_file"
        fi
    done < <(cat "$doc_file")

    mv "$temp_file" "$doc_file"
    echo "Wrote section ${section_id} (${agent_name})"
}

# Get section content
get_section() {
    local doc_name="$1"
    local section_id="$2"
    local doc_file="${OUTPUT_DIR}/${doc_name}.md"

    if [[ ! -f "$doc_file" ]]; then
        echo "Document not found"
        return 1
    fi

    awk "/${SECTION_START} ${section_id} -->/,/${SECTION_END}/ {if (!/<!--/) print}" "$doc_file"
}

# Merge all sections into final document
merge_doc() {
    local doc_name="$1"
    local doc_file="${OUTPUT_DIR}/${doc_name}.md"

    if [[ ! -f "$doc_file" ]]; then
        echo "Document not found"
        return 1
    fi

    echo "# Merged Document"
    echo ""
    echo "*Generated: $(date '+%Y-%m-%d %H:%M:%S')*"
    echo ""

    # Extract all section content
    awk "/${SECTION_START} /,/${SECTION_END}/ {if (!/<!--/) print}" "$doc_file"
}

# Check completion status
check_status() {
    local doc_name="$1"
    local doc_file="${OUTPUT_DIR}/${doc_name}.md"

    if [[ ! -f "$doc_file" ]]; then
        echo "Document not found"
        return 1
    fi

    echo "=== Document Status ==="
    grep -E "<!-- Writer:|<!-- Status:" "$doc_file"
}

# Example workflow
show_example() {
    cat <<'EOF'
# MOA Collaborative Writing Example

## Workflow:

1. Initialize document:
   collab_writer.sh init my_paper

2. Register sections for agents:
   collab_writer.sh register my_paper intro agent_alpha
   collab_writer.sh register my_paper methods agent_beta
   collab_writer.sh register my_paper experiments agent_gamma

3. Agents write to their sections:
   collab_writer.sh write my_paper intro agent_alpha "# Introduction\n..."
   collab_writer.sh write my_paper methods agent_beta "# Methods\n..."
   collab_writer.sh write my_paper experiments agent_gamma "# Experiments\n..."

4. Check status:
   collab_writer.sh status my_paper

5. Merge final document:
   collab_writer.sh merge my_paper > final_paper.md

EOF
}

case "$1" in
    init)
        init_doc "$2"
        ;;
    register)
        register_section "$2" "$3" "$4"
        ;;
    write)
        write_section "$2" "$3" "$4" "$5"
        ;;
    read|get)
        get_section "$2" "$3"
        ;;
    merge)
        merge_doc "$2"
        ;;
    status)
        check_status "$2"
        ;;
    example)
        show_example
        ;;
    *)
        echo "Usage: collab_writer.sh {init|register|write|read|merge|status|example}"
        echo ""
        show_example
        ;;
esac